language: python
python:
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-all libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install nose
  - pip install numpy
  - pip install Cython
  # mpmath for scipy.special tests
  - pip install mpmath
  - python -V
install:
  - "pip install --use-mirrors -r requirements.txt"
script:
  - "nosetests -c nose.cfg"
notifications:
  email: false