language: python
python:
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
env:
  global:
    - PYTHONIOENCODING=UTF8
    - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - PYTHONPATH=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages:/usr/local/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH
before_install:
  - echo $PYTHONENCODING
  - echo $SITE_PKG_DIR
  - echo $PYTHONPATH
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get update -qq
  - sudo apt-get install python3-all python3-numpy python3-scipy python3-nose python3-sphinx libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - python -V
  - pip list
install:
  - pip install --use-mirrors -r requirements.txt
  - pip list
script:
  - "nosetests -c nose.cfg"
notifications:
  email: false