language: python
python:
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-all libatlas-dev libatlas-base-dev liblapack-dev gfortran
#  - pip install nose
#  - pip install numpy
#  - pip install Cython
  # mpmath for scipy.special tests
#  - pip install mpmath
#  - pip install scipy
  - python -V
  - pip list
install:
  - pip install --use-mirrors -r requirements.txt
  - pip list
script:
  - "nosetests -c nose.cfg"
notifications:
  email: false