language: python
python:
  - "3.2"
  - "3.3"
before_install:
  - "sudo apt-get update"
install:
  - "sudo apt-get install gcc gfortran python-dev atlas3-base-dev"
  - "pip install --use-mirrors -r requirements.txt"
script:
  - "nosetests -c nose.cfg"