version: 1
formatters:
  simple:
    format: '%(levelname)s %(module)s.%(funcName)s: %(message)s'
    datefmt: '%d.%m.%y %H:%M:%S %z'
  precise:
    format: '%(asctime)s - %(levelname)s - %(module)s.%(filename)s.%(funcName)s:%(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    level: INFO
    filename: logconfig.log
    maxBytes: 1024
    backupCount: 3
loggers:
  consoleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
  logfileLogger:
    level: INFO
    handlers: [file]
root:
  level: DEBUG
  handlers: [console]
